name: node
app: node@16
name: react
app: web
options:
  docbase: /build
  nodeversion: "20"
  spa: true
context:
  git:
    url: https://github.com/cloudtype-examples/react.git
    branch: main
  preset: react